version: 2

# CalVer tags (YYYY.MM.DD) are not semver.
git:
  tag_sort: -creatordate
  no_strict_semver: true

builds:
  - main: .
    binary: rig
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  use: github
  sort: asc

release:
  github:
    owner: ryan-rushton
    name: rig
